# === Parâmetros de População ===
pop_size: [1.0, 2.0]           # Mantém 2 opções
seed: [42]                     # Valor fixo

# === Parâmetros de Blocos ===
initial_blocks: [0.2]          # Valor padrão
min_block_len: [3]             # Valor comum
rediv_freq: [10]               # Valor intermediário

# === Operadores Genéticos ===
cross_prob: [0.7, 0.9]         # Mantém 2 opções
crossover_type: ['uniform']    # Valor padrão
mut_prob: [0.1]                # Valor intermediário
mutation_type: ['multi', 'inversion']  # Mantém 2 opções
mutation_multi_n: [2]          # Valor padrão
elite_rate: [0.02, 0.1]        # Mantém 2 opções
tournament_k: [3]              # Valor padrão

# === Diversidade e Imigrantes ===
immigrant_freq: [10]           # Valor padrão
immigrant_ratio: [0.2]         # Valor padrão
diversity_threshold: [0.4]     # Valor padrão
mutation_adapt_N: [10]         # Valor padrão
mutation_adapt_factor: [2.0]   # Valor padrão
mutation_adapt_duration: [10]  # Valor padrão

# === Niching (Nichos) ===
niching: [False]               # Valor padrão
niching_radius: [3]            # Valor padrão

# === Refinamento Local ===
refinement_type: ['greedy']    # Valor padrão
refine_elites: ['best']        # Valor padrão
refine_iter_limit: [50]        # Valor padrão

# === Critérios de Parada e Reinício ===
max_gens: [200, 400]           # Mantém 2 opções
max_time: [600.0]              # Valor padrão
no_improve_patience: [0.2]     # Valor padrão
restart_patience: [10]         # Valor padrão
restart_ratio: [0.3]           # Valor padrão
disable_elitism_gens: [0]      # Valor padrão
