# ===================================================================
# CONFIGURAÇÃO PRINCIPAL CSPBench
# ===================================================================

# Configurações da aplicação
application:
  name: "CSPBench"
  version: "0.1.0"
  description: "Framework para Closest String Problem"

# Configurações de infraestrutura
infrastructure:
  # Repositório de datasets
  dataset_repository:
    type: "FileDatasetRepository"
    config:
      base_path: "./datasets"
      supported_formats: ["fasta", "txt"]
  
  # Registry de algoritmos
  algorithm_registry:
    type: "DomainAlgorithmRegistry"
    config:
      auto_register: true
  
  # Executor de algoritmos
  executor:
    type: "Executor"
    config:
      timeout_default: 300
  
  # Sistema de logging
  logging:
    base_log_dir: "./outputs/logs"
    session_folder_format: "%Y%m%d_%H%M%S"
    default_log_level: "INFO"
    log_filename: "cspbench.log"
    create_session_folders: true
    
  # Sistema de resultados
  result:
    base_result_dir: "./outputs/results"
    save_partial_results: false       # Salvar resultados parciais durante execução
    session_folder_format: "%Y%m%d_%H%M%S"  # Mesmo formato dos logs
    create_session_folders: true      # Criar pastas por sessão
    
    # Configurações de relatório
    report:
      save_plots: true
      plot_format: "png"
      calculate_statistics: true
      include_summary: true
      save_detailed_results: true
      
    # Configurações de exportação
    export:
      export_csv: true
      export_json: true

  # Sistema de histórico
  history:
    save_history: false               # Salvar histórico detalhado
    history_frequency: 1              # Frequência de salvamento (a cada N iterações)